app-sre/automated-actions

- .dockerignore
- .gitignore
- .tekton/main-pull-request.yaml
- .tekton/main-push.yaml
- .tool-versions
- Dockerfile
- LICENSE
- Makefile
- README.md
- automated_actions/__main__.py
- pyproject.toml
- renovate.json
- tests/test_main.py
> :rocket: init

- .gitignore
- Dockerfile
- app.sh
- automated_actions/__main__.py
- automated_actions/api/__init__.py
- automated_actions/api/v1/__init__.py
- automated_actions/api/v1/models.py
- automated_actions/api/v1/noop/models.py
- automated_actions/api/v1/noop/views.py
- automated_actions/config.py
- automated_actions/dependencies.py
- pyproject.toml
- uv.lock
> :art: basic project layout

- Makefile
- README.md
- automated_actions_cli/README.md
- automated_actions_cli/automated_actions_cli/__main__.py
- automated_actions_cli/automated_actions_cli/cli.py
- automated_actions_cli/automated_actions_cli/commands/test.py
- automated_actions_cli/automated_actions_cli/config.py
- automated_actions_cli/pyproject.toml
- automated_actions_client/README.md
- automated_actions_client/automated_actions_client/__init__.py
- automated_actions_client/automated_actions_client/api/__init__.py
- automated_actions_client/automated_actions_client/api/v1/run_foobar_action.py
- automated_actions_client/automated_actions_client/api/v1/run_noop_action.py
- automated_actions_client/automated_actions_client/client.py
- automated_actions_client/automated_actions_client/errors.py
- automated_actions_client/automated_actions_client/models/__init__.py
- automated_actions_client/automated_actions_client/models/action.py
- automated_actions_client/automated_actions_client/models/http_validation_error.py
- automated_actions_client/automated_actions_client/models/noop_param.py
- automated_actions_client/automated_actions_client/models/validation_error.py
- automated_actions_client/automated_actions_client/types.py
- automated_actions_client/pyproject.toml
- uv.lock
Add stub `automated-actions-client` (the Python API client) and `automated-actions-cli` (the CLI tool).
> :sparkles: automated-actions API client and cli tool

- packages/automated_actions_cli/automated_actions_cli/utils.py
> add missing utils file

- packages/automated_actions/automated_actions/api/v1/auth.py
- packages/automated_actions/pyproject.toml
> default policies for me and task related actions

- app.sh
- openshift/template.yaml
Add OpenShift template.
Ticket: [APPSRE-11614](https://issues.redhat.com/browse/APPSRE-11614)
> :rocket: openshift template

- openshift/template.yaml
> add pod disruption budget

- packages/automated_actions/automated_actions/api/v1/auth.py
- packages/automated_actions/automated_actions/config.py
don't fail if no policy file is available
> no policy file

- openshift/template.yaml
> :bug: fix typo in template

- Dockerfile
- openshift/template.yaml
- **fix typo in template**
- **automated-actions image: use ubi-minimal to reduce the image size**
> use ubi-minimal

- openshift/template.yaml
- **fix typo in template**
- **reduce probe periods**
> reduce probe periods

- packages/automated_actions_client/automated_actions_client/models/task_status.py
> Fix client task status enumeration

- .tekton/automated-actions-cli-main-pull-request.yaml
- .tekton/automated-actions-cli-main-push.yaml
- .tekton/automated-actions-client-main-pull-request.yaml
- .tekton/automated-actions-client-main-push.yaml
- .tekton/automated-actions-main-pull-request.yaml
- .tekton/automated-actions-main-push.yaml
- .tekton/opa-main-pull-request.yaml
- .tekton/opa-main-push.yaml
> :green_heart: ci: konflux service account

- packages/opa/authz/default_roles.yml
- packages/opa/authz/rbac_default_roles_test.rego
- packages/opa/authz/user_test.rego
> :passport_control: opa: s/task/action/g

- openshift/template.yaml
> openshift template: mark some params as non-required

- packages/automated_actions/automated_actions/api/v1/views/openshift.py
- packages/automated_actions/automated_actions/auth.py
- packages/automated_actions/automated_actions/utils/openshift_client.py
- packages/automated_actions/automated_actions/utils/vault_client.py
- packages/automated_actions/pyproject.toml
- packages/automated_actions/tests/auth/conftest.py
- packages/automated_actions/tests/auth/test_bearer_token_auth.py
- packages/automated_actions/tests/auth/test_opa.py
- packages/automated_actions/tests/auth/test_openid_connect.py
- packages/automated_actions/tests/conftest.py
- packages/automated_actions/tests/test_config.py
- packages/automated_actions/tests/utils/test_cluster_connection.py
- packages/automated_actions/tests/utils/test_gql_client.py
- packages/automated_actions/tests/utils/test_openshift_client.py
- packages/automated_actions/tests/utils/test_vault_client.py
- packages/automated_actions_cli/pyproject.toml
- packages/automated_actions_client/pyproject.toml
- uv.lock
Add unit tests for several modules.
> :white_check_mark: unittests

- .tekton/integration-tests-main-pull-request.yaml
- .tekton/integration-tests-main-push.yaml
- Dockerfile.integration_tests
- packages/automated_actions/pyproject.toml
- packages/automated_actions_client/pyproject.toml
- packages/integration_tests/Makefile
- packages/integration_tests/README.md
- packages/integration_tests/pyproject.toml
- packages/integration_tests/tests/test_cli.py
- pyproject.toml
- uv.lock
This PR adds the integration test "framework" and some basic CLI tests.
> :sparkles: integration tests

- openshift/integration-tests.yaml
Openshift template for the integration tests.
> :rocket: [integration-tests] OpenShift template

- dev/roles.yml
- docker-compose.yml
- packages/automated_actions/automated_actions/api/v1/dependencies.py
- packages/automated_actions/automated_actions/api/v1/views/openshift.py
- packages/automated_actions/automated_actions/db/models/_action.py
- packages/automated_actions/tests/api/v1/views/test_openshift.py
- packages/automated_actions/tests/db/test_model_action.py
- packages/automated_actions_cli/automated_actions_cli/cli.py
- packages/automated_actions_client/automated_actions_client/api/v1/openshift_workload_restart.py
- packages/automated_actions_client/automated_actions_client/models/__init__.py
- packages/automated_actions_client/automated_actions_client/models/openshift_workload_restart_kind.py
- packages/integration_tests/pyproject.toml
- packages/integration_tests/tests/conftest.py
- packages/integration_tests/tests/test_actions.py
- packages/integration_tests/tests/test_cli.py
- packages/integration_tests/tests/test_views_user.py
- uv.lock
Add some more integration tests:
* test `/me`
* test `openShift-workload-restart` action
Additionally, fix some bugs and refactor the get action object dependency.
> :white_check_mark: more unit and integration tests

- openshift/integration-tests.yaml
Bump default memory limit for the integration tests.
> :zap: [integration-tests] increase default mem limit

- openshift/integration-tests.yaml
- packages/integration_tests/tests/conftest.py
Add missing template variables
> [integration-tests] add env vars to OpenShift template

- openshift/integration-tests.yaml
Fix the integration-tests template
> :bug: [integration-tests] fix template

- packages/automated_actions/automated_actions/celery/automated_action_task.py
- packages/automated_actions/automated_actions/db/models/_action.py
- packages/automated_actions/tests/api/v1/views/test_action.py
- packages/automated_actions/tests/celery/test_openshift_workload_restart.py
- packages/automated_actions_client/automated_actions_client/models/__init__.py
- packages/automated_actions_client/automated_actions_client/models/action_schema_out.py
- packages/automated_actions_client/automated_actions_client/models/action_schema_out_task_args.py
- uv.lock
This will help understanding what actions actually do and help debugging.
client code has been generated via Makefile target
> Store celery task kwargs in the action table

- openshift/integration-tests.yaml
Refactor test parameter in the `integration-tests` template. Use a generic `AA_TEST_PARAMETERS` json parameter and "expand" it into a `ConfigMap`
> :recycle: [integration-tests] refactor template

- openshift/template.yaml
Add OPA throttling config to Openshift template and format that file.
> openshift-template: OPA config

- openshift/template.yaml
> :bug: [opa] fix API URL in template

- packages/automated_actions/pyproject.toml
- packages/automated_actions_cli/pyproject.toml
- packages/automated_actions_client/pyproject.toml
- packages/integration_tests/pyproject.toml
- packages/integration_tests/tests/test_cli.py
- uv.lock
Fix CLI integration tests after switching default output to `yaml`
> :white_check_mark: [integration-tests] fix cli tests

- packages/automated_actions/automated_actions/db/models/_action.py
- packages/automated_actions/automated_actions/db/models/_user.py
Rename tables to have them sorted in the AWS console UI
> [automated-actions] rename tables

- packages/automated_actions_cli/automated_actions_cli/cli.py
- packages/automated_actions_cli/automated_actions_cli/config.py
> :recycle: [cli] --url option

- openshift/integration-tests.yaml
fixing 436629144dc9709ae3d5e25e5decf406154033ac
> fix integration tests template

- packages/automated_actions/pyproject.toml
- packages/automated_actions_cli/pyproject.toml
- packages/automated_actions_client/pyproject.toml
- packages/automated_actions_utils/pyproject.toml
- packages/integration_tests/pyproject.toml
- uv.lock
> :arrow_up: upgrade dependencies

- Dockerfile.integration_tests
- openshift/integration-tests.yaml
> Allow for Int tests template to run certain tests

- docker-compose.yml
- packages/automated_actions/automated_actions/api/v1/views/action.py
- packages/automated_actions/automated_actions/api/v1/views/no_op.py
- packages/automated_actions/automated_actions/api/v1/views/openshift.py
- packages/automated_actions_client/automated_actions_client/api/v1/action_cancel.py
- packages/automated_actions_client/automated_actions_client/api/v1/action_detail.py
- packages/automated_actions_client/automated_actions_client/api/v1/action_list.py
- packages/automated_actions_client/automated_actions_client/api/v1/create_token.py
- packages/automated_actions_client/automated_actions_client/api/v1/me.py
- packages/automated_actions_client/automated_actions_client/api/v1/no_op.py
- packages/automated_actions_client/automated_actions_client/api/v1/openshift_workload_restart.py
- packages/automated_actions_client/openapi_python_client_templates/typer_command.py.jinja
... and update/refine some action descriptions.
> :memo: support multiline action descriptions

- Makefile
- packages/integration_tests/pyproject.toml
- packages/integration_tests/tests/actions/test_no_op.py
- packages/integration_tests/tests/conftest.py
- uv.lock
Introduce two new pytest fixtures to simplify action triggering and enhance support for flaky tests.
> :recycle: [integration-tests] some refactoring

- docs/development-guides/implementing-new-actions.md
Add a checklist, mention qontract-reconcile, qontract-schemas and app-interface integration tests config.
> :memo: [automated-actions] update new action doc

- dashboards/metrics-dashboard.yaml
> Metrics Dashboard

- dashboards/logs-dashboard.yaml
> Logs dashboard

- packages/automated_actions_utils/automated_actions_utils/vault_client.py
- packages/automated_actions_utils/tests/test_vault_client.py
We use now a more direct method. The replaced one didn't work well with our current hvac version.
APPSRE-12232
> Fix get vault get mount version

- packages/automated_actions_utils/automated_actions_utils/gql_client.py
- packages/automated_actions_utils/pyproject.toml
- uv.lock
> :arrow_up: upgrade gql
