app-sre/automated-actions

- .tekton/automated-actions-cli-main-push.yaml
- .tekton/automated-actions-client-main-push.yaml
`image-expires-after` isn't allowed for releases.
> :green_heart: fix CI build

- openshift/template.yaml
- packages/opa/authz/rbac.rego
- packages/opa/authz/rbac_test.rego
Comparing the requests params must be case-insensitive.
> :bug: opa: case insensitive params match

- packages/automated_actions_client/pyproject.toml
- uv.lock
Change to upstream openapi-python-client because https://github.com/openapi-generators/openapi-python-client/issues/1188 has been fixed.
> :arrow_up: automated-actions-client: use upstream openapi-python-client

- packages/automated_actions/pyproject.toml
- uv.lock
Install newer `h11` because of this [CVE](https://github.com/python-hyper/h11/security/advisories/GHSA-vqfr-h8mv-ghfj)
> :arrow_up: bump dependencies

- packages/automated_actions/pyproject.toml
- uv.lock
uv sync --all-packages complains
```
× No solution found when resolving dependencies:
╰─▶ Because automated-actions:dev depends on qenerate==0.7.0 and qenerate==0.7.0 depends
on graphql-core>=3.2.5,<3.3.dev0, we can conclude that automated-actions:dev depends on
graphql-core>=3.2.5,<3.3.dev0.
And because gql==3.5.2 depends on graphql-core>=3.2,<3.2.5 and automated-actions depends on gql==3.5.2, we can
conclude that automated-actions and automated-actions:dev are incompatible.
And because your workspace requires automated-actions and automated-actions:dev, we can conclude that your
workspace's requirements are unsatisfiable.
```
> gql back to 3.5.0, 3.5.2 conflicts with qenerate

- openshift/integration-tests.yaml
Add missing `IMAGE_PULL_SECRETS` variable.
```
File "/work/reconcile/utils/openshift_resource.py", line 451, in <listcomp>
if "-dockercfg-" not in s["name"]
~^^^^^^^^
TypeError: string indices must be integers, not 'str'
```
> :bug: [integration-tests] fix OpenShift template

- Dockerfile.integration_tests
Fix
```
error: failed to remove file `/opt/app-root/lib/python3.12/site-packages/integration_tests-0.1.0.dist-info/INSTALLER`: Permission denied (os error 13)
```
> :bug: [integration-tests] fix permission errors

- packages/automated_actions/automated_actions/celery/automated_action_task.py
- packages/automated_actions/tests/celery/test_openshift_workload_restart.py
Tests are built calling the task synchronously so that we test the whole
celery setup without the need of the broker or the worker, being the
test case and the real world very close.
I have removed the reload messages from the custom base class because
it is intended to be generic. This introduces the need of keeping
somewhere else the details of the invocation, in this case the cluster,
namespace, kind and name of the workload restarted.
Signed-off-by: Rafa Porres Molina <rporresm@redhat.com>
> tests for openshift-workload-reload celery task

- packages/integration_tests/pyproject.toml
`pytest-asyncio` isn't used for the integration tests.
> [integration-tests] remove obsolete pytest config

- packages/automated_actions/automated_actions/config.py
- packages/automated_actions/automated_actions/db/models/_action.py
- packages/automated_actions/automated_actions/db/models/_user.py
- packages/automated_actions/tests/conftest.py
- packages/automated_actions/tests/test_config.py
And use it to make sure we create different dynamodb tables per environment in case we use the same AWS account for different accounts.
> Set environment variable

- Dockerfile
- Dockerfile.cli
- Dockerfile.client
- Dockerfile.integration_tests
- Dockerfile.opa
- packages/automated_actions/automated_actions/config.py
- packages/automated_actions_cli/automated_actions_cli/cli.py
- packages/automated_actions_cli/automated_actions_cli/formatter.py
- packages/automated_actions_cli/pyproject.toml
- packages/automated_actions_cli/tests/test_formatter.py
- packages/automated_actions_cli/tests/test_stub.py
- packages/automated_actions_client/automated_actions_client/api/v1/action_cancel.py
- packages/automated_actions_client/automated_actions_client/api/v1/action_detail.py
- packages/automated_actions_client/automated_actions_client/api/v1/action_list.py
- packages/automated_actions_client/automated_actions_client/api/v1/create_token.py
- packages/automated_actions_client/automated_actions_client/api/v1/me.py
- packages/automated_actions_client/automated_actions_client/api/v1/openshift_workload_restart.py
- packages/automated_actions_client/openapi_python_client_templates/typer_command.py.jinja
- uv.lock
This PR refactors the CLI output format and colors.
* `--output` to specify the output format.
* `--color/--no-color` to enable/disable colorized outputs 
Additionally, this PR pins the `click` package because of https://github.com/fastapi/typer/pull/1145
Ticket: [APPSRE-12006](https://issues.redhat.com/browse/APPSRE-12006)
> 🎉 [automated-actions-cli] output format

- packages/automated_actions/automated_actions/api/v1/views/action.py
- packages/automated_actions/automated_actions/api/v1/views/openshift.py
- packages/automated_actions/automated_actions/auth.py
- packages/automated_actions/automated_actions/db/models/_action.py
- packages/automated_actions/tests/api/v1/views/test_action.py
- packages/automated_actions/tests/db/test_model_action.py
- packages/automated_actions_cli/automated_actions_cli/formatter.py
- packages/automated_actions_cli/tests/test_formatter.py
- packages/automated_actions_client/automated_actions_client/api/v1/action_cancel.py
- packages/automated_actions_client/automated_actions_client/api/v1/action_detail.py
- packages/automated_actions_client/automated_actions_client/api/v1/action_list.py
- packages/automated_actions_client/automated_actions_client/api/v1/create_token.py
- packages/automated_actions_client/automated_actions_client/api/v1/me.py
- packages/automated_actions_client/automated_actions_client/api/v1/openshift_workload_restart.py
- packages/automated_actions_client/openapi_python_client_templates/typer_command.py.jinja
- packages/opa/Makefile
- packages/opa/authz/default_roles.yml
- packages/opa/authz/rbac.rego
- packages/opa/authz/rbac_default_roles_test.rego
- uv.lock
This PR refactors the `action-list` endpoint:
1. **:passport_control: [opa] support authorization on query params**
The default roles don't allow the usage of `action_user` for `action-list`
2. **:sparkles: [automated-actions] action-list supports action_user param**
Support listing action for `action_user` and make `status` an optional parameter. The default is to list all actions for the currently logged-in user.
**Breaking change**
We use `username` instead of `email` for `action.owner`. 
**Others**
Additionally, this PR fixes the CLI formatter for list responses.
Prerequisite for https://issues.redhat.com/browse/APPSRE-12021
> action-list: action_user param 

- openshift/template.yaml
- packages/automated_actions/automated_actions/api/__init__.py
- packages/opa/authz/rate_limit.rego
- packages/opa/authz/rate_limit_test.rego
* A `max_ops: 0` also indicates no rate limit on the action.
* do not skip authz for `me`
> authorization fixes

- packages/automated_actions/automated_actions/api/__init__.py
The cookie setting `ensure_https` must be independent of the `DEBUG` settings. Inspect the `URL` instead.
> :bug: [automated-actions] fix cookie https only setting in dev env

- openshift/integration-tests.yaml
Fix error
```
[2025-06-03 02:15:21] [ERROR] [DRY-RUN] [saasherder.py:_process_template:968] - [saas-automated-actions-test/automated-actions] https://github.com/app-sre/automated-actions/blob/f9675e3a92b3dd5bac0f6101193efc95aee67d33/openshift/integration-tests.yaml: error processing template: [None]: error: failed to read input object (not a Template?): unable to decode "STDIN": json: cannot unmarshal array into Go struct field Parameter.parameters.value of type string
```
https://github.com/app-sre/automated-actions/pull/136
> fix: quote openshift template value for ARGS

- packages/automated_actions_cli/Makefile
- packages/automated_actions_client/Makefile
Release the `automated-actions-cli` and `automated-actions-client` packages to PyPI.
> :tada: [automated-actions-cli/client] enable PyPI releases

- dashboards/metrics-dashboard.yaml
- packages/automated_actions/automated_actions/celery/metrics.py
To better match the actual duration of the action processing.
> Redistribute action elapsed seconds bucket

- Dockerfile.cli
We want to support running the `automated-actions` CLI as a Docker image as a 3rd "installation" method.
> :sparkles: [automated-actions-cli] install kerberos in the image

- packages/automated_actions/automated_actions/celery/app.py
- packages/automated_actions/automated_actions/celery/automated_action_task.py
- packages/automated_actions/automated_actions/celery/openshift/tasks.py
Add the `action_id` automatically to all Celery logs (if available).
Example:
```
2025-06-24 09:26:00,343 [INFO] celery.worker.consumer.connection: Connected to sqs://localstack:4566// action_id=unknown
2025-06-24 09:26:00,417 [INFO] celery.apps.worker: celery@9f219a80164b ready. action_id=unknown
2025-06-24 09:26:15,062 [INFO] celery.worker.strategy: Task automated_actions.celery.openshift.tasks.openshift_workload_restart[b084de65-6ef6-46d1-81fa-90170ba82058] received action_id=unknown
2025-06-24 09:26:15,145 [INFO] automated_actions.celery.openshift.tasks.openshift_workload_restart: status=RUNNING action_id=b084de65-6ef6-46d1-81fa-90170ba82058
2025-06-24 09:26:16,592 [INFO] automated_actions.celery.openshift.tasks.openshift_workload_restart: Restarting OpenShift workload Deployment …
```
> :loud_sound: [automated-actions] action_id in the logs

- app.sh
- settings.md
Separate the auto-reload feature of FastAPI and Celery from the `AA_DEBUG` flag. Using a dedicated config makes it clearer and prevents debug messages from cluttering the logs.
> AA_AUTO_RELOAD config

- Dockerfile.cli
- Dockerfile.client
- packages/automated_actions_cli/Makefile
- packages/automated_actions_client/Makefile
Unfortunately, [buildah](https://github.com/containers/buildah/issues/5892) doesn't support the `env` option for `RUN --mount=type=secret`. Let's try setting this env variable manually instead.
> fix pypi push

- packages/automated_actions_client/pyproject.toml
- uv.lock
Renovate can't create PRs because of `openapi-python-client`. 
```
Using CPython 3.12.9 interpreter at: /usr/bin/python3
× No solution found when resolving dependencies:
╰─▶ Because openapi-python-client==0.26.1 depends on typer>0.6,<0.18 and
automated-actions-client:dev depends on openapi-python-client==0.26.1,
we can conclude that automated-actions-client:dev depends on
typer>0.6,<0.18.
And because automated-actions-cli depends on typer==0.19.2, we can
conclude that automated-actions-cli and automated-actions-client:dev
are incompatible.
And because your workspace requires automated-actions-cli and
automated-actions-client:dev, we can conclude that your workspace's
requirements are unsatisfiable.
```
We can reenable the dependency if …
> temporary disable openapi-python-client dependency

- compose.yml
- packages/automated_actions_client/automated_actions_client/api/actions/external_resource_flush_elasticache.py
- packages/automated_actions_client/automated_actions_client/api/actions/external_resource_rds_reboot.py
- packages/automated_actions_client/automated_actions_client/api/actions/external_resource_rds_snapshot.py
- packages/automated_actions_client/automated_actions_client/api/actions/no_op.py
- packages/automated_actions_client/automated_actions_client/api/actions/openshift_workload_delete.py
- packages/automated_actions_client/automated_actions_client/api/actions/openshift_workload_restart.py
- packages/automated_actions_client/automated_actions_client/api/admin/create_token.py
- packages/automated_actions_client/automated_actions_client/api/general/action_cancel.py
- packages/automated_actions_client/automated_actions_client/api/general/action_detail.py
- packages/automated_actions_client/automated_actions_client/api/general/action_list.py
- packages/automated_actions_client/automated_actions_client/api/general/me.py
- packages/automated_actions_client/automated_actions_client/models/action_schema_out.py
- packages/automated_actions_client/automated_actions_client/models/create_token_param.py
- packages/automated_actions_client/automated_actions_client/models/http_validation_error.py
- packages/automated_actions_client/automated_actions_client/models/user_schema_out.py
- packages/automated_actions_client/automated_actions_client/models/validation_error.py
- packages/automated_actions_client/openapi_python_client_templates/endpoint_module.py.jinja
- packages/automated_actions_client/openapi_python_client_templates/types.py.jinja
- packages/automated_actions_client/pyproject.toml
This PR upgrades the openapi-python-client dependency from version 0.25.3 to 0.26.2. The upgrade modifies how the client is installed and used, moving from a direct dependency to using a specific version in the compose.yml file to avoid conflicts with outdated typer dependencies that can break Renovate.
> :arrow_up: upgrade openapi-python-client
